SELECT 
    TO_CHAR(e.DATE_ADDED, 'YYYY-MM') as MONTH_YEAR,
    COUNT(*) as TRANSACTION_COUNT,
    SUM(e.AMOUNT) as TOTAL_SPENT,
    ROUND(AVG(e.AMOUNT), 2) as AVG_TRANSACTION_SIZE,
    COUNT(DISTINCT ec.EVENT_ID) as ACTIVE_EVENTS,
    COUNT(DISTINCT e.VENDOR_NAME) as ACTIVE_VENDORS,
    ROUND(
        (SUM(e.AMOUNT) - LAG(SUM(e.AMOUNT), 1) OVER (ORDER BY TO_CHAR(e.DATE_ADDED, 'YYYY-MM'))) / 
        NULLIF(LAG(SUM(e.AMOUNT), 1) OVER (ORDER BY TO_CHAR(e.DATE_ADDED, 'YYYY-MM')), 0) * 100, 2
    ) as MONTHLY_GROWTH_RATE
FROM EXPENSES e
JOIN EXPENSE_CATEGORIES ec ON e.CATEGORY_ID = ec.CATEGORY_ID
WHERE e.DATE_ADDED >= ADD_MONTHS(SYSDATE, -6)
GROUP BY TO_CHAR(e.DATE_ADDED, 'YYYY-MM')
ORDER BY MONTH_YEAR DESC;
