SELECT 
    -- Summary metrics
    (SELECT COUNT(*) FROM AUDIT_LOG) as TOTAL_OPERATIONS,
    (SELECT COUNT(*) FROM AUDIT_LOG WHERE STATUS = 'DENIED') as DENIED_OPERATIONS,
    (SELECT COUNT(*) FROM AUDIT_LOG WHERE STATUS = 'SUCCESS') as ALLOWED_OPERATIONS,
    ROUND(
        (SELECT COUNT(*) FROM AUDIT_LOG WHERE STATUS = 'SUCCESS') / 
        NULLIF((SELECT COUNT(*) FROM AUDIT_LOG), 0) * 100, 2
    ) as COMPLIANCE_RATE_PERCENT,
    
    -- Time analysis
    TO_CHAR(OPERATION_DATE, 'Day') as DAY_OF_WEEK,
    EXTRACT(HOUR FROM OPERATION_DATE) as HOUR_OF_DAY,
    COUNT(*) as OPERATIONS_COUNT,
    
    -- User analysis
    USER_NAME,
    COUNT(*) as USER_OPERATIONS,
    COUNT(CASE WHEN STATUS = 'DENIED' THEN 1 END) as USER_DENIALS
    
FROM AUDIT_LOG
WHERE OPERATION_DATE >= SYSDATE - 30
GROUP BY 
    TO_CHAR(OPERATION_DATE, 'Day'),
    EXTRACT(HOUR FROM OPERATION_DATE),
    USER_NAME
ORDER BY OPERATIONS_COUNT DESC;
