SELECT 
    CREATED_BY as USER_ID,
    COUNT(*) as TOTAL_EVENTS,
    SUM(TOTAL_BUDGET) as TOTAL_BUDGET_ALLOCATED,
    SUM(ACTUAL_SPENDING) as TOTAL_SPENT,
    
    -- Budget adherence
    COUNT(CASE WHEN ACTUAL_SPENDING <= TOTAL_BUDGET THEN 1 END) as EVENTS_WITHIN_BUDGET,
    COUNT(CASE WHEN ACTUAL_SPENDING > TOTAL_BUDGET THEN 1 END) as EVENTS_OVER_BUDGET,
    ROUND(
        COUNT(CASE WHEN ACTUAL_SPENDING <= TOTAL_BUDGET THEN 1 END) / 
        NULLIF(COUNT(*), 0) * 100, 2
    ) as WITHIN_BUDGET_PERCENT,
    
    -- Budget utilization
    ROUND(
        AVG(CASE WHEN TOTAL_BUDGET > 0 
             THEN ACTUAL_SPENDING / TOTAL_BUDGET * 100 
             ELSE 0 END), 2
    ) as AVG_BUDGET_UTILIZATION,
    
    -- Success classification
    CASE 
        WHEN AVG(CASE WHEN TOTAL_BUDGET > 0 
                  THEN ACTUAL_SPENDING / TOTAL_BUDGET * 100 
                  ELSE 0 END) BETWEEN 70 AND 90 
             AND COUNT(CASE WHEN ACTUAL_SPENDING <= TOTAL_BUDGET THEN 1 END) / 
                 NULLIF(COUNT(*), 0) * 100 >= 90 THEN 'EXPERT'
        WHEN AVG(CASE WHEN TOTAL_BUDGET > 0 
                  THEN ACTUAL_SPENDING / TOTAL_BUDGET * 100 
                  ELSE 0 END) BETWEEN 50 AND 90 
             AND COUNT(CASE WHEN ACTUAL_SPENDING <= TOTAL_BUDGET THEN 1 END) / 
                 NULLIF(COUNT(*), 0) * 100 >= 75 THEN 'COMPETENT'
        WHEN COUNT(CASE WHEN ACTUAL_SPENDING <= TOTAL_BUDGET THEN 1 END) / 
             NULLIF(COUNT(*), 0) * 100 >= 50 THEN 'LEARNING'
        ELSE 'NEEDS_GUIDANCE'
    END as USER_SUCCESS_LEVEL
    
FROM EVENTS
GROUP BY CREATED_BY
ORDER BY AVG_BUDGET_UTILIZATION DESC;
