WITH resource_metrics AS (
    SELECT 
        -- Database Statistics
        (SELECT COUNT(*) FROM user_tables) as TOTAL_TABLES,
        (SELECT COUNT(*) FROM user_indexes) as TOTAL_INDEXES,
        
        -- Table Row Counts
        (SELECT COUNT(*) FROM EVENTS) as EVENTS_COUNT,
        (SELECT COUNT(*) FROM EXPENSES) as EXPENSES_COUNT,
        (SELECT COUNT(*) FROM EXPENSE_CATEGORIES) as CATEGORIES_COUNT,
        (SELECT COUNT(*) FROM AUDIT_LOG) as AUDIT_COUNT,
        (SELECT COUNT(*) FROM HOLIDAYS) as HOLIDAYS_COUNT,
        
        -- Storage Estimates (KB)
        (SELECT COUNT(*) FROM EVENTS) * 1.0 as EVENTS_KB,
        (SELECT COUNT(*) FROM EXPENSES) * 0.5 as EXPENSES_KB,
        (SELECT COUNT(*) FROM EXPENSE_CATEGORIES) * 0.25 as CATEGORIES_KB,
        (SELECT COUNT(*) FROM AUDIT_LOG) * 0.25 as AUDIT_KB,
        (SELECT COUNT(*) FROM HOLIDAYS) * 0.12 as HOLIDAYS_KB,
        
        -- Performance Metrics
        (SELECT COUNT(*) FROM EXPENSES) as TOTAL_TRANSACTIONS,
        ROUND((SELECT COALESCE(AVG(AMOUNT), 0) FROM EXPENSES), 2) as AVG_TRANSACTION_AMOUNT,
        
        -- Date Analysis
        (SELECT MIN(DATE_ADDED) FROM EXPENSES) as FIRST_TRANSACTION,
        (SELECT MAX(DATE_ADDED) FROM EXPENSES) as LAST_TRANSACTION,
        ROUND(SYSDATE - (SELECT MAX(DATE_ADDED) FROM EXPENSES), 1) as DAYS_SINCE_LAST
        
    FROM dual
)
SELECT 
    -- Database Summary
    TOTAL_TABLES,
    TOTAL_INDEXES,
    EVENTS_COUNT + EXPENSES_COUNT + CATEGORIES_COUNT + AUDIT_COUNT + HOLIDAYS_COUNT as TOTAL_ROWS,
    
    -- Storage Analysis
    ROUND((EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) / 1024, 2) as TOTAL_STORAGE_MB,
    ROUND(EVENTS_KB / 1024, 2) as EVENTS_MB,
    ROUND(EXPENSES_KB / 1024, 2) as EXPENSES_MB,
    ROUND(CATEGORIES_KB / 1024, 2) as CATEGORIES_MB,
    ROUND(AUDIT_KB / 1024, 2) as AUDIT_MB,
    
    -- Storage Percentage
    ROUND(EVENTS_KB / (EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) * 100, 1) as EVENTS_PERCENT,
    ROUND(EXPENSES_KB / (EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) * 100, 1) as EXPENSES_PERCENT,
    
    -- Performance Metrics
    TOTAL_TRANSACTIONS,
    AVG_TRANSACTION_AMOUNT,
    
    -- Growth Projection (2.1% monthly growth)
    ROUND((EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) / 1024 * POWER(1.021, 6), 2) as PROJECTED_6MONTH_MB,
    ROUND((EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) / 1024 * POWER(1.021, 12), 2) as PROJECTED_12MONTH_MB,
    
    -- Time to reach 10MB threshold
    ROUND(LOG(10, 1.021) / LOG((EVENTS_KB + EXPENSES_KB + CATEGORIES_KB + AUDIT_KB + HOLIDAYS_KB) / 1024, 1.021), 1) as MONTHS_TO_10MB
    
FROM resource_metrics;
